// Code generated by go-bindata. DO NOT EDIT.
//  memcopy: true
//  compress: true
//  decompress: once
//  asset-dir: true
//  restore: true
// sources:
//  users/migrations/1_initial_schema.down.sql
//  users/migrations/1_initial_schema.up.sql

package migrations

import (
	"bytes"
	"compress/flate"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/tmthrgd/go-bindata/restore"
)

type asset struct {
	name string
	data string
	size int64

	once  sync.Once
	bytes []byte
	err   error
}

func (a *asset) Name() string {
	return a.name
}

func (a *asset) Size() int64 {
	return a.size
}

func (a *asset) Mode() os.FileMode {
	return 0
}

func (a *asset) ModTime() time.Time {
	return time.Time{}
}

func (*asset) IsDir() bool {
	return false
}

func (*asset) Sys() interface{} {
	return nil
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]*asset{
	"1_initial_schema.down.sql": &asset{
		name: "1_initial_schema.down.sql",
		data: "" +
			"\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2d\x4e" +
			"\x2d\x2a\x56\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\x82\xa8\x89\x0c\x70\x55\x28\xca\xcf\x49\xb5\xe6" +
			"\x02\x04\x00\x00\xff\xff",
		size: 52,
	},
	"1_initial_schema.up.sql": &asset{
		name: "1_initial_schema.up.sql",
		data: "" +
			"\x64\xce\xc1\x6a\x84\x40\x0c\x06\xe0\xfb\x3c\xc5\x7f\x73\x85\x7d\x83\x3d\x4d\x77\x53\x3a\x54\x47" +
			"\x19\x33\xb4\xf6\x22\x76\x0d\x22\x74\x74\x19\xf5\xd0\xb7\x2f\x1d\xda\xa5\xd0\x4b\x48\x48\xbe\x24" +
			"\x67\x47\x9a\x09\xf4\xca\x64\x1b\x53\x59\xdc\xc6\x6b\xfc\xbc\x6d\xcb\x49\xa9\x9f\x1e\xb7\x35\x21" +
			"\x2e\x1f\x02\xdd\x80\xac\x2f\x71\xc8\xc6\x5d\xd6\x2d\x3b\x22\x0b\x12\xde\x25\x7e\x67\xfd\x10\xa6" +
			"\x39\xcb\xff\x38\xfd\x50\x10\xf6\x55\xe2\x8a\x83\x02\x80\x69\x80\xf7\xe6\x82\xda\x99\x52\xbb\x16" +
			"\xcf\xd4\xe2\x42\x8f\xda\x17\x8c\x51\xe6\x2e\xf6\xf3\xb0\x84\x6e\xdf\xa7\xe1\x90\x1f\x13\x49\x77" +
			"\x53\xb0\x15\xc3\xfa\xa2\xb8\x8b\xdf\x27\xd2\xdc\x35\x4a\xbf\x49\xb7\x4d\x41\xc0\xa6\xa4\x86\x75" +
			"\x59\xe3\xc5\xf0\x53\x2a\xf1\x56\x59\xfa\xbf\xe2\xec\x9d\x23\xcb\xdd\x5d\xa8\xfc\xa4\xbe\x02\x00" +
			"\x00\xff\xff",
		size: 275,
	},
}

// AssetAndInfo loads and returns the asset and asset info for the
// given name. It returns an error if the asset could not be found
// or could not be loaded.
func AssetAndInfo(name string) ([]byte, os.FileInfo, error) {
	a, ok := _bindata[filepath.ToSlash(name)]
	if !ok {
		return nil, nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	a.once.Do(func() {
		fr := flate.NewReader(strings.NewReader(a.data))

		var buf bytes.Buffer
		if _, a.err = io.Copy(&buf, fr); a.err != nil {
			return
		}

		if a.err = fr.Close(); a.err == nil {
			a.bytes = buf.Bytes()
		}
	})
	if a.err != nil {
		return nil, nil, &os.PathError{Op: "read", Path: name, Err: a.err}
	}

	return a.bytes, a, nil
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	a, ok := _bindata[filepath.ToSlash(name)]
	if !ok {
		return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	data, _, err := AssetAndInfo(name)
	return data, err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}

	return names
}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	return restore.Asset(dir, name, AssetAndInfo)
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	return restore.Assets(dir, name, AssetDir, AssetAndInfo)
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree

	if name != "" {
		var ok bool
		for _, p := range strings.Split(filepath.ToSlash(name), "/") {
			if node, ok = node[p]; !ok {
				return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
			}
		}
	}

	if len(node) == 0 {
		return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	rv := make([]string, 0, len(node))
	for name := range node {
		rv = append(rv, name)
	}

	return rv, nil
}

type bintree map[string]bintree

var _bintree = bintree{
	"1_initial_schema.down.sql": bintree{},
	"1_initial_schema.up.sql":   bintree{},
}
