// Code generated by go-bindata. DO NOT EDIT.
//  memcopy: true
//  compress: true
//  decompress: once
//  asset-dir: true
//  restore: true
// sources:
//  users/migrations/1_initial_schema.down.sql
//  users/migrations/1_initial_schema.up.sql

package migrations

import (
	"bytes"
	"compress/flate"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/tmthrgd/go-bindata/restore"
)

type asset struct {
	name string
	data string
	size int64

	once  sync.Once
	bytes []byte
	err   error
}

func (a *asset) Name() string {
	return a.name
}

func (a *asset) Size() int64 {
	return a.size
}

func (a *asset) Mode() os.FileMode {
	return 0
}

func (a *asset) ModTime() time.Time {
	return time.Time{}
}

func (*asset) IsDir() bool {
	return false
}

func (*asset) Sys() interface{} {
	return nil
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]*asset{
	"1_initial_schema.down.sql": &asset{
		name: "1_initial_schema.down.sql",
		data: "" +
			"\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2d\x4e" +
			"\x2d\x2a\x56\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\x82\xa8\x89\x0c\x70\x55\x28\xca\xcf\x49\xb5\xe6" +
			"\x02\x04\x00\x00\xff\xff",
		size: 52,
	},
	"1_initial_schema.up.sql": &asset{
		name: "1_initial_schema.up.sql",
		data: "" +
			"\x64\xce\xc1\x6a\xc3\x30\x0c\x06\xe0\xbb\x9f\xe2\xbf\x25\x81\xbe\x41\x4f\x5e\xab\xb1\xb0\xc4\x0d" +
			"\xae\xcc\xc8\x2e\x26\x9b\x45\x31\xcc\x29\x38\xf1\xfb\x8f\x19\xda\xcb\x2e\x42\x02\x7d\xd2\x7f\xb2" +
			"\xa4\x99\xc0\xf3\x44\xc8\xf7\x1f\x81\xbe\x82\x8c\x1b\xd1\x36\xb7\x22\xdb\xde\x1c\xd0\x24\x49\x5f" +
			"\x92\xff\xba\x25\xa4\xb8\x36\xdd\x51\xa9\x87\xd3\x2f\x03\xa1\x6c\x92\x37\xb4\x0a\x00\x62\x80\x73" +
			"\xfd\x19\x93\xed\x47\x6d\x67\xbc\xd3\x8c\x33\xbd\x6a\x37\x30\x6e\xb2\xfa\xbc\xac\xe1\x9e\x7c\x29" +
			"\x31\xb4\xdd\xa1\x92\xfa\xb7\x16\x73\x61\x18\x37\x0c\x4f\xf1\x08\x51\xf7\xbe\xb3\x2c\xbb\xf8\x3d" +
			"\x26\x01\xf7\x23\x5d\x59\x8f\x13\x3e\x7a\x7e\xab\x23\x3e\x2f\x86\xfe\x9f\x38\x39\x6b\xc9\xb0\x7f" +
			"\x0a\xd5\x1d\xd5\x6f\x00\x00\x00\xff\xff",
		size: 247,
	},
}

// AssetAndInfo loads and returns the asset and asset info for the
// given name. It returns an error if the asset could not be found
// or could not be loaded.
func AssetAndInfo(name string) ([]byte, os.FileInfo, error) {
	a, ok := _bindata[filepath.ToSlash(name)]
	if !ok {
		return nil, nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	a.once.Do(func() {
		fr := flate.NewReader(strings.NewReader(a.data))

		var buf bytes.Buffer
		if _, a.err = io.Copy(&buf, fr); a.err != nil {
			return
		}

		if a.err = fr.Close(); a.err == nil {
			a.bytes = buf.Bytes()
		}
	})
	if a.err != nil {
		return nil, nil, &os.PathError{Op: "read", Path: name, Err: a.err}
	}

	return a.bytes, a, nil
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	a, ok := _bindata[filepath.ToSlash(name)]
	if !ok {
		return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	data, _, err := AssetAndInfo(name)
	return data, err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}

	return names
}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	return restore.Asset(dir, name, AssetAndInfo)
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	return restore.Assets(dir, name, AssetDir, AssetAndInfo)
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree

	if name != "" {
		var ok bool
		for _, p := range strings.Split(filepath.ToSlash(name), "/") {
			if node, ok = node[p]; !ok {
				return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
			}
		}
	}

	if len(node) == 0 {
		return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
	}

	rv := make([]string, 0, len(node))
	for name := range node {
		rv = append(rv, name)
	}

	return rv, nil
}

type bintree map[string]bintree

var _bintree = bintree{
	"1_initial_schema.down.sql": bintree{},
	"1_initial_schema.up.sql":   bintree{},
}
