// Code generated by sqlc. DO NOT EDIT.

package users

import (
	"fmt"
	"time"

	"github.com/jackc/pgtype"
)

type Role string

const (
	RoleGuest  Role = "guest"
	RoleMember Role = "member"
	RoleAdmin  Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type User struct {
	ID         pgtype.UUID
	Role       Role
	CreateTime time.Time
	Name       string
}
