// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (
  role,
  name
) VALUES (
  $1, 
  $2
)
RETURNING id, role, create_time, name
`

type AddUserParams struct {
	Role Role
	Name string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Role, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreateTime,
		&i.Name,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, role, create_time, name
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreateTime,
		&i.Name,
	)
	return i, err
}
